version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: gpt
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d gpt"]
        interval: 10s
        timeout: 5s
        retries: 5

  app:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./:/app
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
